### ISSUE TITLE
シーン遷移基板設計と実装

### ISSUE THREAD

**Issue by Rapilias** [Rapilias/documents#1]
## 概要
ロード表示、メモリ展開/破棄要素等、シーン遷移時に必要な要素について洗い出して設計及び実装を行う。
**起動時のロードについてもこのissueで考慮する**

**Comment by Rapilias** [comment]
## 要素
### シーン
+ シーン識別名/Id
+ 事前読み込み可能なシーン内では解放されないアセット群(以下`PreloadAssts`) 原則Addressable

### 遷移フロー
- [ ] アクティブシーン開放
- [ ] ロード用シーンへ移行
- [ ] `PreloadAsset`の読み出し
- [ ] 次シーン展開

### I/F
- [ ] `LoadScene`
  - 現シーンを開放し、ロード用シーンへと移行して`PreloadAsset`と次シーンの展開を待機 
- [ ] `PreloadSceneAssetAsync`
  -  指定したシーン(アクティブシーン除く)に関連づいた`PreloadAsset`を読んでメモリに展開のみ行う
  - ロードのキャンセルは`CancellationToken`経由で行い、ロードが完了した場合は下記関数を利用する
- [ ] `UnloadSceneAssetAsync`
  - 指定したシーンに関連づいた`PreloadAsset`のメモリに展開済みのデータを開放する

各シーンの初期化は`LifeTimeScope`を通じて行う 他シーンからデータを渡す場合(セーブデータなど)も`GameLifeTimeScope` -> `{SceneName}LifeTimeScope`とInjectすることで行いたいが実装フェーズで要検証

### 起動時
+ `RuntimeInitializeOnLoadMethod`で`StartUp`を起動
+ `MessagePackResolver` / `MasterMemory`の展開
+ **ゲーム自体の`PreloadAsset`** (フォントとかUI共通とか)のロード
  + もし時間が掛かるならロード用シーンへ飛ばす
+ SplashScreen表示( #10 )

**Comment by Egliss** [comment]
`ScriptableObject`な`PreloadAsset`を用意
対応シーン or global preloadの識別子と`AssetReference`の配列を保持する
これでStartUp内で全ての`ScriptableObject`を読んでglobal preloadのみその場でロード
それ以外の物は各Preloadに応じてロードする

**Comment by Rapilias** [comment]
`Addressables.DownloadDependencies`がやりたいことそのものだったのでこちらへ置き換え

**Comment by Rapilias** [comment]
`DownloadDependencies`、よくよく読むと依存関係の解決しかしないらしく、アセットのロードとは関係無し
`LoadAssetsAsync` は型指定が必須、 `object`だと弾かれたためどうするか要検討

**Comment by Egliss** [comment]
`LoadAssetsAsync `をベースに実装完了

**Comment by Rapilias** [comment]
`LoadAssetsAsync` をベースに実装完了
