### ISSUE TITLE
Questの達成度変化を良い感じにする

### ISSUE THREAD

**Issue by Rapilias** [Rapilias/documents#114]
## 概要
#95 の表示が味気ないのでわかりやすくする

**Comment by Egliss** [comment]
![text_anim_1](https://user-images.githubusercontent.com/37934691/156352746-37f63919-8c03-41d6-9b7c-3a0bce8b21a0.gif)
ないよりはマシだが正直あんまり変わらない感があるのでもう少し工夫が欲しい

**Comment by Rapilias** [comment]
![text_anim_1](https://user-images.githubusercontent.com/91034223/156353040-9235f8b3-55ef-4944-a155-c7d474f0d54e.gif)
無いよりマシだが微妙感が否めない

**Comment by Rapilias** [comment]
達成度自体は一旦このまま
開始/完了等は別issue
