### ISSUE TITLE
SCHALEモデリング

### ISSUE THREAD

**Issue by Rapilias** [Rapilias/documents#145]
## 概要
シャーレのモデリングを行う
暫定目標として
+ 30万Tri 以下
+ 100Material以下

辺り
不定期にランタイムに持ち込んでパフォーマンスを見ていく

**Comment by Egliss** [comment]
> 100Material以下

現状の制作手法では無理 
メッシュ構築後にテクスチャ/マテリアルをある程度オブジェクトのグループでマージするなどの対策が必要

**Comment by Rapilias** [comment]
現状の制作手法では無理
いくつかのオブジェクトを1グループとしてテクスチャアトラスを割ったりTexture2DArray等に突っ込む必要がある
